name: movie_flutter

on:
  pull_request:
    # paths:
    #   - "**.dart"
  push:
    # paths:
    #   - "**.dart"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: flutter packages get

      # - name: Generate Environment Config
      #   run: flutter pub run environment_config:generate

      - name: Generate Build Runners
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 70
          exclude: "**/*.g.dart **/*.freezed.dart **/*.config.dart lib/env_config.dart"
